version: '3'

services:
   app:
      build: .
      container_name: golang
      volumes:
         - .:/go/src/app
      ports:
         - '8000:8000'

      networks:
         - rede1

networks:
   rede1:
      name: rede1
      driver: bridge
